cat_features:
- group_node_name
- start_node_name
- end_node_name
- road_name
- day_of_week
- base_hour
- road_rating
- start_turn_restricted
- end_turn_restricted
- rush_hour
selected_features:
- 오현고앞삼거리_거로마을
- 제주민속식품가공공장_대천동사거리
- 천제이교_천제이교
- 인다마을_아라주공아파트
- 서사라사거리_한국병원앞
- 문예회관사거리_인제사거리
- 서흥사거리_경동보일러
- 서울이용원_남양리조트
- 해안육교_해안동804-4
- 서홍교_서흥동사무소
- 서흥동사무소_서홍교
- 동홍사거리_서귀포교육청
- 삼주연립101동_민우연립1동
- 한국통신_우체국
- 중앙여고사거리_연북5교
- 해안교_해안육교
- 오장교_오봉교
- 동홍교_동홍5차아파트504동
- 봉개교 시종점_부록교 시종점
- 제2거로교_제2거로교
- 제2성읍교_제2성읍교
- 서홍교_서홍교
- 월산정수장입구_월산마을
- 종합경기장사거리_삼오교
- 도순2교_도순3교
- 우체국_한국통신
- 한국통신_한국통신
- 전망대_선방석재개발(주)
- 중앙교_중앙교
- 중앙여고사거리_제주여중고입구사거리
- 색달동마을_색달동
- 고평교_고평교
- 제5산록교_제6산록교
- 어승생삼거리_어승생삼거리
- 신양약방_중문한의원
- 종합운동장입구사거리_동산교
- 월평교앞교차로_동샘교차로
- 와흘교차로_회천교차로
- 서귀포시산림조합_중산간도로삼거리
- 수악교_수악교
- 대흥개발(주)_성카인테리어
- 서귀포경찰서_의료보험조합
- 월산정수장입구_한라대학입구
- 삼양교(서측)_다이소제주화북점
- 명도암교차로_봉개교차로
- 대륜동주민센터_시청입구1
- 봉개교 시종점_봉개교 시종점
- 부동산_서귀포시청
- 영주교_영주교
- 도두동입구_도두삼거리
- 뉴본아파트_선경오피스텔
- 제주삼다수_제4교래교
- 창천교_창천삼거리
- 제주시 삼양2동 2186-1_삼양동사무소
- 관광단지입구_중문입구
- 성산교차로_고성교차로
- 서귀포시산림조합_청룡개발
- 한라대학입구_월산정수장입구
- 세미마을입구_남조로교차로
- 진동1로_동중입구
- 한남투자_정방수퍼
- 고성교차로_성산교차로
- 현사마을_이호해수욕장입
- 서사라사거리_삼오교
- 새마을회관_마을창고
- 시청입구1_월드컵경기장
- 예래입구_산신주유소
- 큰집솥뚜껑_오름식당
- 흘천5교_그랜드호텔사거
- 중문농협_대림한숲빌라112동
- 팔도철물건재_서현주택
- 한국병원앞_제2오라교
- 도순3교_도순2교
- 관광단지입구_산신주유소
- 산신주유소_중문한의원
- 천혜빌딩_제주렌트카
- 천제이교_야영장
- 서귀포시청_부동산
- 야영장_전망대
- 민속마을입구교차로_제2성읍교
- 의료보험조합_서귀포경찰서
- 도순교_대천동사무소
- 해안교_무수천제2교
- 삼무공원입구사거리_신광사거리
- 야영장_천제이교
- 성카인테리어_대흥개발(주)
- 제주시 삼양2동 1480-2_삼양검은모래해변입구교차로
- 우체국_의료보험조합
- 산신주유소_산신주유소
- 도순3교_도순3교
- 인제사거리_영락교회
- 오라교_한국병원앞
- 신성교회_서호2차현대맨션203동
- 천제이교_불목케
- 오라오거리_제3한천교
- 제6산록교_제5산록교
- 수모루_수모루교차로
- 인제사거리_문예회관사거리
- 서호2차현대맨션203동_신성교회
- 제2산록도로_제6산록교
- 오름식당_큰집솥뚜껑
- 용당교차로_수모루교차로
- 호남석재사거리_문예회관사거리
- 법원사거리_소방서앞사거리
- 남양리조트_서현주택
- 회천교차로_와흘교차로
- 정방수퍼_BYC
- 세무서사거리_법원사거리
- 부영아파트_제주일고
- 제2오라교_한국병원앞
- 동수교_동수교
- 도근교_월산마을
- 외도천교_외도천교
- 강정동 163_신성교회
- 청룡개발_서귀포시산림조합
- 효례교_청송낚시
- 우성사료_정방수퍼
- 자운당교_덕진건재
- 제주여중고입구사거리_중앙여고사거리
- 동중입구_진동1로
- 수악교_윤고교
- 색달교_색달교
- 선방석재개발(주)_선방석재개발(주)
- 강정동 163_국민의료보험관리공단
- 중문입구삼거리_자운당교
- 제5산록교_제5산록교
- 제6산록교_제6산록교
- 삼양검은모래해변입구교차로_삼양동사무소
- 자운당교_중문입구삼거리
- 수모루교차로_용당교차로
- 삼성의원사거리_동광장교
- 동홍사거리_대흥개발(주)
- 수복당_청상어식당
- 동홍교_서운사거리
- 제주은행사거리_산지2교
- 제주일고_부영아파트
- 서호2차현대맨션203동_시청입구2
- 연동사거리_신제주초교입구오거리
- 우성사료_서귀포교육청
- 광덕아파트_사라봉오거리
- 정방수퍼_우성사료
- 선방석재개발(주)_전망대
- 삼주연립101동_한솔고기국수
- 동중입구_다이소제주화북점
- 세훈빌리지_중문입구
- 노형오거리_노형파출소
- 문예회관사거리_호남석재사거리
- 천혜빌딩_한국통신
- 염광아파트_달무교차로
- 대원교_대원교
- 월산1교_월산2교
- 제5산록교_제4산록교
- 제2서홍교_제2서홍교
- 민우연립1동_중문농협
- 이호동입구1_이호해수욕장입
- 봉개교 시종점_대기고앞삼거리
- 서귀포교육청_우성사료
- 우성아파트사거리_거로사거리
- 해안마을_제1해안교
- 대기고앞삼거리_봉개교 시종점
- 난방시공협회_시민공원
- 하례입구삼거리_영주교
- 선경오피스텔_정방수퍼
- 대흥개발(주)_동홍사거리
- 시청입구1_대륜동주민센터
- 제주삼다수_육성목장
- 제2거로교_제3거로교
- 삼주연립101동_시청입구1
- 별도교_제주교대
- 제주렌트카_중문농협
- 삼오교_종합경기장사거리
- 영주교_하례입구삼거리
- 난지농업연구소삼거리_한북교
- 동홍5차아파트528동_서흥사거리
- 선경오피스텔_뉴본아파트
- 시민공원_서귀포경찰서
- 동홍5차아파트504동_동홍5차아파트528동
- 자유도시민박_색달동
- 제1성읍교_제주민속식품가공공장
- 마을창고_새마을회관
- 거로사거리_우성아파트사거리
- 부부식당_팔도철물건재
- 달무교차로_염광아파트
- 내도동입구_현사마을
- 삼양교(서측)_삼양교(동측)
- 광양사거리_KAL사거리
- 경동보일러_서흥사거리
- 전망대_야영장
- 윤고교_윤고교
- 윤고교_동수교
- 해안동804-4_해안육교
- 하천교차로_광전출하반
- 도순2교_도순2교
- 중문한의원_산신주유소
- 다이소제주화북점_동중입구
- 제주렌트카_천혜빌딩
- 동홍새마을금고_온누리부동산
- 명도암교차로_버으내교차로
- 제4산록교_제4산록교
- 시민공원_난방시공협회
- 연북2교_연북2교
- 윤고교_수악교
- 월산마을_도근교
- 삼양교(동측)_삼양교(서측)
- 한전아파트_덕수사거리
- 제6산록교_제2산록도로
- BYC_정방수퍼
- 관음사길_관음교
- 도평마을_내도동입구
- 한북교_난지농업연구소삼거리
- 서흥사거리_동홍5차아파트528동
- 국립제주박물관_영락교회
- 중문농협_민우연립1동
- 삼양검은모래해변입구교차로_제주시 삼양2동 1480-2
- 회수입구_중문입구삼거리
- 동광장교_문예회관사거리
- 서중입구_오일장입구
- 다이소제주화북점_삼양교(서측)
- 덕수사거리_한전아파트
- 불목케_천제이교
- 월산2교_월산1교
- 성산교차로_신양교차로
- 한솔고기국수_삼주연립101동
- 광전출하반_하천교차로
- 한북교_한북교
- 월드컵경기장_시청입구2
- 이호동입구1_이호동입구2
- 오라오거리_동산교
- 동산교_오라오거리
- 아라초등학교앞_제2아라교
- 중문한의원_신양약방
- 외도연대마을_외도1동
- 큰집솥뚜껑_한솔고기국수
- 시청입구2_월드컵경기장
- 색달교_색달동마을
- 진동1로_화북남문입구삼거리
- 중문입구_세훈빌리지
- 오렌지농원_영주교
- BYC_김약국
- 동수교_윤고교
- 중문입구_관광단지입구
- 반딧불식당_동홍새마을금고
- 부부식당_수복당
- 칠오광장사거리_마리나사거리
- 염광아파트_인다마을
- 관음교_관음사길
- 서호2차현대맨션203동_대림한숲빌라112동
- 제4산록교_제5산록교
- 한국통신_천혜빌딩
- 남당동_화순삼거리
- 이호해수욕장입_현사마을
- 사라봉오거리_광덕아파트
- 제4교래교_제주삼다수
- 대천동사무소_도순교
- 대천동사거리_대원교
- 동홍5차아파트504동_동홍교
- 삼양동사무소_제주시 삼양2동 2186-1
- 동홍새마을금고_반딧불식당
- 창천교_창천교
- 중문입구삼거리_회수입구
- 온누리부동산_동홍새마을금고
- 육성목장_제주삼다수
- 연북5교_중앙여고사거리
- 월드컵경기장_시청입구1
- 청송낚시_효례교
- 마리나사거리_칠오광장사거리
- 중산간도로삼거리_서귀포시산림조합
- 창천삼거리_창천교
- 한국통신_부동산
- 제2회수교_제2회수교
- 무수천제2교_해안교
- 민우연립1동_삼주연립101동
- 제일성읍교_제1성읍교
- 서현주택_남양리조트
- 돈내코유원지입구_하례입구삼거리
- 동홍교_동홍교
- 부록교 시종점_봉개교 시종점
- 영주교_오렌지농원
- 대원교_선흘입구
- 국립제주박물관_거로사거리
- 부동산_오름식당
- 색달동마을_색달교
- 상효2교_상효2교
- 별도교_거로마을
- 회수입구_회수사거리
- 중문농협_중문농협
- 인다마을_염광아파트
- 내도동입구_도평마을
- 우남육교_우남육교
- 김약국_BYC
- 덕진건재_자운당교
- 노루생이_노루생이삼거리
- 회수사거리_회수입구
- 현사마을_내도동입구
- 오렌지빌라B동_서운사거리
- 제2성읍교_성읍2리
- 오라오거리_오라3동
- 도노교_보건소사거리
- 서운사거리_동홍교
- 수모루교차로_수모루
- 의료보험조합_우체국
- 제2거로교_거로사거리
- 월산마을_월산정수장입구
- 월산1교_월산1교
- 제1해안교_해안육교
- 외도1동_외도연대마을
- 색달동_색달동마을
- 동광장교_삼성의원사거리
- 정방수퍼_한남투자
- 어리목입구_어리목입구
- 제1해안교_해안마을
- 오봉교_오장교
- 아라주공아파트_인다마을
- 산신주유소_예래입구
- 서울이용원_뉴본아파트
- 산신주유소_관광단지입구
- 제2아라교_아라초등학교앞
- 오름식당_부동산
- 그랜드호텔사거_흘천5교
- 의료보험조합_국민의료보험관리공단
- 선경오피스텔_반딧불식당
- 노형파출소_노형오거리
- 정방수퍼_선경오피스텔
- 소방서앞사거리_법원사거리
- 남양리조트_서울이용원
- 시청입구1_삼주연립101동
- 노루생이삼거리_노루생이
- 용흥교(동측)_강정교
- 반딧불식당_선경오피스텔
- 수복당_부부식당
- 대림한숲빌라112동_중문농협
- 월산2교_월산2교
- 제주교대_별도교
- 보건소사거리_도노교
- 부동산_한국통신
- 제1성읍교_제1성읍교
- 팔도철물건재_부부식당
- 외도서부교회_외도연대마을
- 서귀포경찰서_시민공원
- 오라3동_오라오거리
- 대림한숲빌라112동_서호2차현대맨션203동
- 국민의료보험관리공단_의료보험조합
- 문예회관사거리_동광장교
- 뉴본아파트_서울이용원
- 신광사거리_삼무공원입구사거리
- 산지2교_제주은행사거리
- 영락교회_국립제주박물관
- 서현주택_팔도철물건재
- 법원사거리_세무서사거리
- 도순교_도순교
- 삼오교_서사라사거리
- 신효교_신효교
- 화순삼거리_남당동
- 색달동_자유도시민박
- 외도연대마을_외도서부교회
- 한국병원앞_오라교
- 어시천교_어시천교
- 강정교_용흥교(동측)
- 신제주초교입구오거리_연동사거리
- 한솔고기국수_큰집솥뚜껑
- 외도교_외도교
- 도두삼거리_도두동입구
- 색달육교_색달육교
- 중문농협_제주렌트카
- 한국병원앞_서사라사거리
- 서귀포교육청_동홍사거리
- 시청입구2_서호2차현대맨션203동
- 동산교_종합운동장입구사거리
- 오일장입구_서중입구
- 제3한천교_오라오거리
- 해안육교_제1해안교
- 거로사거리_국립제주박물관
- 하례입구삼거리_돈내코유원지입구
- 제3거로교_제2거로교
- 동샘교차로_월평교앞교차로
- 화북남문입구삼거리_진동1로
- 서운사거리_오렌지빌라B동
- 거로마을_오현고앞삼거리
- 삼성교_호남석재사거리
- 해안교_해안교
- 거로사거리_제2거로교
- 거로마을_별도교
- 호남석재사거리_삼성교
- 성카인테리어_오렌지빌라B동
- 부록교 시종점_부록교 시종점
- 동홍5차아파트528동_동홍5차아파트504동
- 국민의료보험관리공단_강정동 163
- 신양교차로_성산교차로
- 이호동입구2_이호동입구1
- 해안육교_해안교
- 신성교회_강정동 163
- 버으내교차로_명도암교차로
- 이호해수욕장입_이호동입구1
- 자운당교_자운당교
- 삼양동사무소_삼양검은모래해변입구교차로
- 청상어식당_수복당
- 영락교회_인제사거리
- KAL사거리_광양사거리
- 오렌지빌라B동_성카인테리어
- 제2성읍교_민속마을입구교차로
