cat_features:
- day_of_week
- base_hour
- road_rating
- start_turn_restricted
- end_turn_restricted
- connect_code
- maximum_speed_limit
- weight_restricted
- road_type
- group_node
task_type: GPU
params:
  iterations: 20000
  learning_rate: 0.4
  thread_count: -1
  l2_leaf_reg: 10
  loss_function: MAE
  eval_metric: MAE
  posterior_sampling: False
  allow_writing_files: False
path: res/models/
working: catboost
name: 5fold_catboost
n_splits: 5
early_stopping_rounds: 100
search: False
seed: 42
verbose_eval: 500
result: 5fold_catboost_kmeans_seed42.pkl