cat_features:
- day_of_week
- start_turn_restricted
- end_turn_restricted
- start_node_name
- end_node_name
- group_node
task_type: CPU
params:
  iterations: 10000
  depth: 6
  learning_rate: 0.3
  thread_count: -1
  l2_leaf_reg: 10
  loss_function: MAE
  eval_metric: MAE
  posterior_sampling: False
path: res/models/
working: catboost
name: 5fold_catboost
n_splits: 5
early_stopping_rounds: 100
search: False
seed: 42
verbose_eval: 500
result: 5fold_catboost_seed42.pkl