task_type: GPU
params:
  iterations: 10000
  depth: 6
  learning_rate: 0.025
  thread_count: -1
  l2_leaf_reg: 10
  loss_function: MAE
  boosting_type: Plain
  eval_metric: MAE
  posterior_sampling: False
path: res/models/
working: catboost
name: 5fold_catboost
n_splits: 5
early_stopping_rounds: 100
search: False
seed: 42
verbose_eval: 500
result: 5fold_catboost_seed42.pkl