cat_features:
- day_of_week
- base_hour
- road_rating
- start_turn_restricted
- end_turn_restricted
- connect_code
- maximum_speed_limit
- weight_restricted
- road_type
- group_node
n_splits: 5
params:
  objective: mae
  metric: mae
  boosting_type: gbdt
  learning_rate: 0.35
  num_leaves: 606
  max_depth: 7
  lambda_l2: 0.06506676052501416
  lambda_l1: 0.036210622617823776
  colsample_bytree: 0.4241631237880101
  subsample: 0.8876057928391585
  subsample_freq: 5
  min_child_samples: 37
  seed: 42
  verbose: -1
path: res/models/
working: lightgbm
name: 5fold_lightgbm_cat
early_stopping_rounds: 100
num_boost_round: 20000
verbose_eval: 500
result: 5fold_lightgbm_cat_seed42.pkl