n_splits: 10
params:
  objective: mae
  metric: mae
  boosting_type: gbdt
  learning_rate: 0.05
  num_leaves: 100
  lambda_l2: 0.07127674208132959
  lambda_l1: 5.998770177220496e-05
  colsample_bytree: 0.4241631237880101
  subsample: 0.8876057928391585
  subsample_freq: 5
  min_child_samples: 5
  seed: 42
  verbose: -1
path: res/models/
working: lightgbm
name: 10fold_lightgbm
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100