hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

defaults:
  - data: dataset
  - features: engineering
  - log: wandb
  - models: catboost

output:
  path: output
  lightgbm: 5fold_lightgbm_cat_seed42.csv
  catboost: 5fold_catboost_seed42.csv
  name: median_ensemble.csv
  submit: sample_submission.csv
  features: features.yaml
