defaults:
  - data: dataset
  - features: engineering
  - hydra: default
  - log: wandb
  - models: lightgbm

output:
  path: output
  name: 5fold_lightgbm_kmeans_seed42.csv
  submit: sample_submission.csv
  features: features.yaml
